[book]
authors = ["Joseph"]
language = "en"
multilingual = false
src = "src"
title = "gitcoin-passport"

[build]
build-dir = "book"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds

[output.html]
default-theme = "ayu"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
# additional-css = ["custom.css", "custom2.css"]
# additional-js = ["custom.js"]
no-section-label = false
# git-repository-url = "https://github.com/rust-lang/mdBook"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"
site-url = "/pasport-docs/"
cname = "myproject.rs"
input-404 = "404.md"

[output.html.search]
limit-results = 15

