[book]
authors = ["Joseph"]
language = "en"
multilingual = false
src = "src"
title = "Gitcoin Passport"

[build]
build-dir = "book"                # the directory where the output is placed
create-missing = false             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds

[output.html]

default-theme = "light"
preferred-dark-theme = "ayu"
curly-quotes = true
copy-fonts=false
mathjax-support = false
copy-js = true
additional-css = ["theme/css/custom.css"]
# additional-js = ["custom.js"]
no-section-label = false
git-repository-url = "https://github.com/jmcook1186/gp-passport-docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/jmcook1186/gp-passport-docs"
site-url = "/passport-docs/"
cname = "passport-docs.rs"
input-404 = "404.md"

[output.html.search]
limit-results = 15